name: Automated Markdown Search

on: 
  workflow_dispatch:   # Allows you to run this manually from GitHub Actions tab
  push:                # Runs automatically every time you push new code
    branches:
      - main           # Only runs when changes are made to the main branch

jobs:
  search:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3    # Updated to v3 to avoid Node.js deprecation warnings

    - name: Search for keyword in markdown files
      run: |
        echo "Searching for the keyword 'AI' in markdown files..."
        grep -rni -e "ChatGPT" -e "Generative AI" -e "black box" --include \*.md . || echo "No matches found"



